# -*- coding: utf-8  -*-
import family

__version__ = '$Id$'

# The Wikimedia family that is known as Wiktionary

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'wiktionary'

        self.languages_by_size = [
            'en', 'fr', 'lt', 'zh', 'tr', 'ru', 'vi', 'io', 'pl', 'pt', 'fi',
            'hu', 'el', 'ko', 'no', 'ta', 'de', 'sv', 'it', 'nl', 'kn', 'li',
            'lo', 'ml', 'ja', 'es', 'ku', 'ar', 'et', 'ro', 'id', 'te', 'gl',
            'uk', 'bg', 'ca', 'vo', 'mg', 'fa', 'is', 'scn', 'sr', 'simple',
            'cs', 'af', 'hr', 'th', 'oc', 'fy', 'sw', 'br', 'he', 'la', 'sq',
            'sl', 'hy', 'my', 'tt', 'zh-min-nan', 'da', 'wa', 'ne', 'tk', 'ast',
            'ur', 'hsb', 'cy', 'lv', 'kk', 'ka', 'ky', 'eo', 'wo', 'ang', 'co',
            'hi', 'az', 'ga', 'gn', 'ia', 'eu', 'mr', 'sk', 'ms', 'csb', 'tl',
            'st', 'nn', 'be', 'nds', 'kl', 'sd', 'ug', 'ps', 'ti', 'mk', 'sh',
            'an', 'bn', 'gu', 'si', 'km', 'ss', 'ts', 'qu', 'bs', 'fo', 'am',
            'rw', 'chr', 'su', 'om', 'iu', 'mn', 'nah', 'kw', 'yi', 'ie', 'gv',
            'pa', 'mt', 'gd', 'tg', 'zu', 'tpi', 'dv', 'ik', 'za', 'sg', 'so',
            'lb', 'roa-rup', 'jv', 'uz', 'ln', 'mi', 'sm', 'ha', 'ay', 'sa',
            'na', 'jbo', 'tn', 'fj', 'ks', 'dz', 'als',
        ]

        if family.config.SSL_connection:
            self.langs = dict([(lang, None) for lang in self.languages_by_size])
        else:
            self.langs = dict([(lang, '%s.wiktionary.org' % lang) for lang in self.languages_by_size])

        # Override defaults
        self.namespaces[2]['eo'] = u'Uzanto'
        self.namespaces[3]['eo'] = u'Uzanta diskuto'
        self.namespaces[2]['pl'] = u'Wikipedysta'
        self.namespaces[3]['pl'] = u'Dyskusja Wikipedysty'

        # Most namespaces are inherited from family.Family.
        # Translation used on all wikis for the different namespaces.
        # (Please sort languages alphabetically)
        # You only need to enter translations that differ from _default.
        self.namespaces[4] = {
            '_default': [u'Wiktionary', self.namespaces[4]['_default']],
            'ar': u'ويكاموس',
            'ast': u'Uiccionariu',
            'bg': u'Уикиречник',
            'bn': u'উইকিঅভিধান',
            'br': u'Wikeriadur',
            'bs': u'Vikirječnik',
            'ca': u'Viccionari',
            'cs': u'Wikislovník',
            'cy': u'Wiciadur',
            'el': u'Βικιλεξικό',
            'eo': u'Vikivortaro',
            'es': u'Wikcionario',
            'et': u'Vikisõnastik',
            'fa': u'ویکی‌واژه',
            'fi': u'Wikisanakirja',
            'fo': u'Wiktionary',
            'fr': u'Wiktionnaire',
            'ga': u'Vicífhoclóir',
            'gu': u'વિક્ષનરી',
            'he': u'ויקימילון',
            'hi': u'विक्षनरी',
            'hr': u'Wječnik',
            'hu': u'Wikiszótár',
            'hy': u'Վիքիբառարան',
            'ia': u'Wiktionario',
            'io': u'Wikivortaro',
            'is': u'Wikiorðabók',
            'it': u'Wikizionario',
            'ka': u'ვიქსიკონი',
            'kk': u'Уикисөздік',
            'ko': u'위키낱말사전',
            'la': u'Victionarium',
            'lt': u'Vikižodynas',
            'ml': u'വിക്കിനിഘണ്ടു',
            'ms': u'Wiktionary',
            'mt': u'Wikizzjunarju',
            'nl': u'WikiWoordenboek',
            'oc': u'Wikiccionari',
            'pl': u'Wikisłownik',
            'ps': u'ويکيسيند',
            'pt': u'Wikcionário',
            'ro': u'Wikţionar',
            'ru': u'Викисловарь',
            'scn': u'Wikizziunariu',
            'si': u'වික්ෂනරි',
            'sk': u'Wikislovník',
            'sl': u'Wikislovar',
            'sr': u'Викиречник',
            'tk': u'Wikisözlük',
            'tr': u'Vikisözlük',
            'tt': u'Wiktionary',
            'uk': u'Вікісловник',
            'ur': u'وکی لغت',
            'uz': u'Vikilug‘at',
            'vo': u'Vükivödabuk',
            'yi': [u'װיקיװערטערבוך', u'וויקיווערטערבוך'],
            'zh': [u'Wiktionary', u'维基词典'],
        }

        self.namespaces[5] = {
            '_default': [u'Wiktionary talk', self.namespaces[5]['_default']],
            'ab': u'Обсуждение Wiktionary',
            'af': u'Wiktionarybespreking',
            'als': u'Wiktionary Diskussion',
            'am': u'Wiktionary ውይይት',
            'an': u'Descusión Wiktionary',
            'ar': u'نقاش ويكاموس',
            'ast': u'Uiccionariu alderique',
            'av': u'Обсуждение Wiktionary',
            'ay': u'Wiktionary Discusión',
            'az': u'Wiktionary müzakirəsi',
            'ba': u'Wiktionary б-са фекер алышыу',
            'be': u'Wiktionary размовы',
            'bg': u'Уикиречник беседа',
            'bm': u'Discussion Wiktionary',
            'bn': u'উইকিঅভিধান আলোচনা',
            'br': u'Kaozeadenn Wikeriadur',
            'bs': u'Razgovor s Vikirječnikom',
            'ca': u'Viccionari Discussió',
            'cs': u'Diskuse k Wikislovníku',
            'csb': u'Diskùsëjô Wiktionary',
            'cy': u'Sgwrs Wiciadur',
            'da': u'Wiktionary-diskussion',
            'de': u'Wiktionary Diskussion',
            'el': u'Συζήτηση βικιλεξικού',
            'eo': u'Vikivortaro diskuto',
            'es': u'Wikcionario Discusión',
            'et': u'Vikisõnastiku arutelu',
            'eu': u'Wiktionary eztabaida',
            'fa': u'بحث ویکی‌واژه',
            'fi': u'Keskustelu Wikisanakirjasta',
            'fo': u'Wiktionary-kjak',
            'fr': u'Discussion Wiktionnaire',
            'fy': u'Wiktionary oerlis',
            'ga': u'Plé Vicífhoclóra',
            'gl': u'Conversa Wiktionary',
            'gn': u'Wiktionary myangekõi',
            'gu': u'વિક્ષનરી ચર્ચા',
            'gv': u'Resooney Wiktionary',
            'he': u'שיחת ויקימילון',
            'hi': u'विक्षनरी वार्ता',
            'hr': u'Razgovor Wječnik',
            'hsb': u'Wiktionary diskusija',
            'hu': u'Wikiszótár-vita',
            'hy': u'Վիքիբառարանի քննարկում',
            'ia': u'Discussion Wiktionario',
            'id': u'Pembicaraan Wiktionary',
            'io': u'Wikivortaro Debato',
            'is': [u'Wikiorðabókarspjall', u'Wikiorðabókspjall'],
            'it': u'Discussioni Wikizionario',
            'ja': u'Wiktionary・トーク',
            'jv': u'Dhiskusi Wiktionary',
            'ka': u'ვიქსიკონი განხილვა',
            'kk': u'Уикисөздік талқылауы',
            'kl': u'Wiktionary-p oqalliffia',
            'km': u'ការពិភាក្សាអំពីWiktionary',
            'kn': u'Wiktionary ಚರ್ಚೆ',
            'ko': u'위키낱말사전토론',
            'ku': u'Wiktionary nîqaş',
            'kw': u'Keskows Wiktionary',
            'la': u'Disputatio Victionarii',
            'lb': u'Wiktionary Diskussioun',
            'li': u'Euverlèk Wiktionary',
            'ln': u'Discussion Wiktionary',
            'lo': u'ສົນທະນາກ່ຽວກັບWiktionary',
            'lt': u'Vikižodyno aptarimas',
            'lv': u'Wiktionary diskusija',
            'mg': u'Dinika amin\'ny Wiktionary',
            'mk': u'Разговор за Wiktionary',
            'ml': u'വിക്കിനിഘണ്ടു സംവാദം',
            'mn': u'Wiktionary-н хэлэлцүүлэг',
            'mr': u'Wiktionary चर्चा',
            'ms': u'Perbincangan Wiktionary',
            'mt': u'Diskussjoni Wikizzjunarju',
            'nah': u'Wiktionary tēixnāmiquiliztli',
            'nap': [u'Wiktionary chiàcchiera', u'Discussioni Wiktionary'],
            'nds': u'Wiktionary Diskuschoon',
            'nl': u'Overleg WikiWoordenboek',
            'nn': u'Wiktionary-diskusjon',
            'no': u'Wiktionary-diskusjon',
            'oc': u'Discussion Wikiccionari',
            'pa': u'Wiktionary ਚਰਚਾ',
            'pl': u'Wikidyskusja',
            'ps': u'د ويکيسيند خبرې اترې',
            'pt': u'Wikcionário Discussão',
            'qu': u'Wiktionary rimanakuy',
            'ro': u'Discuție Wikţionar',
            'ru': u'Обсуждение Викисловаря',
            'sa': u'Wiktionaryसंभाषणं',
            'sc': u'Wiktionary discussioni',
            'scn': u'Discussioni Wikizziunariu',
            'sd': u'Wiktionary بحث',
            'sg': u'Discussion Wiktionary',
            'si': u'වික්ෂනරි සාකච්ඡාව',
            'sk': u'Diskusia k Wikislovníku',
            'sl': u'Pogovor o Wikislovarju',
            'sq': u'Wiktionary diskutim',
            'sr': u'Разговор о викиречнику',
            'su': u'Obrolan Wiktionary',
            'sv': u'Wiktionarydiskussion',
            'sw': u'Majadiliano ya Wiktionary',
            'ta': u'Wiktionary பேச்சு',
            'te': u'Wiktionary చర్చ',
            'tg': u'Баҳси Wiktionary',
            'th': u'คุยเรื่องWiktionary',
            'tk': [u'Wikisözlük çekişme', u'Wikisözlük talk'],
            'tl': u'Usapang Wiktionary',
            'tr': u'Vikisözlük tartışma',
            'tt': [u'Wiktionary бәхәсе', u'Wiktionary bäxäse'],
            'uk': u'Обговорення Вікісловника',
            'ur': u'تبادلۂ خیال وکی لغت',
            'uz': u'Vikilug‘at munozarasi',
            'vi': u'Thảo luận Wiktionary',
            'vo': u'Bespik dö Vükivödabuk',
            'wa': u'Wiktionary copene',
            'wo': u'Wiktionary waxtaan',
            'yi': [u'װיקיװערטערבוך רעדן', u'וויקיווערטערבוך רעדן'],
            'za': u'Wiktionary讨论',
            'zh': [u'Wiktionary talk', u'维基词典讨论'],
        }

        self.namespaces[90] = {
            'af': u'Thread',
            'als': u'Thread',
            'am': u'Thread',
            'an': u'Thread',
            'ang': u'Thread',
            'ar': u'Thread',
            'ast': u'Thread',
            'ay': u'Thread',
            'az': u'Thread',
            'be': u'Thread',
            'bg': u'Thread',
            'bn': u'Thread',
            'br': u'Thread',
            'bs': u'Thread',
            'ca': u'Thread',
            'chr': u'Thread',
            'co': u'Thread',
            'cs': u'Thread',
            'csb': u'Thread',
            'cy': u'Thread',
            'da': u'Thread',
            'de': u'Thread',
            'dv': u'Thread',
            'dz': u'Thread',
            'el': u'Thread',
            'en': u'Thread',
            'eo': u'Thread',
            'es': u'Thread',
            'et': u'Thread',
            'eu': u'Thread',
            'fa': u'Thread',
            'fi': u'Viestiketju',
            'fj': u'Thread',
            'fo': u'Thread',
            'fr': u'Thread',
            'fy': u'Thread',
            'ga': u'Thread',
            'gd': u'Thread',
            'gl': u'Tópico',
            'gn': u'Thread',
            'gu': u'Thread',
            'gv': u'Thread',
            'ha': u'Thread',
            'he': u'Thread',
            'hi': u'Thread',
            'hr': u'Thread',
            'hsb': u'Thread',
            'hu': u'Thread',
            'hy': u'Thread',
            'ia': u'Thread',
            'id': u'Thread',
            'ie': u'Thread',
            'ik': u'Thread',
            'io': u'Thread',
            'is': u'Thread',
            'it': u'Thread',
            'iu': u'Thread',
            'ja': u'Thread',
            'jbo': u'Thread',
            'jv': u'Thread',
            'ka': u'Thread',
            'kk': u'Thread',
            'kl': u'Thread',
            'km': u'Thread',
            'kn': u'Thread',
            'ko': u'Thread',
            'ks': u'Thread',
            'ku': u'Thread',
            'kw': u'Thread',
            'ky': u'Thread',
            'la': u'Thread',
            'lb': u'Thread',
            'li': u'Thread',
            'ln': u'Thread',
            'lo': u'Thread',
            'lt': u'Thread',
            'lv': u'Thread',
            'mg': u'Thread',
            'mi': u'Thread',
            'mk': u'Thread',
            'ml': u'Thread',
            'mn': u'Thread',
            'mr': u'Thread',
            'ms': u'Thread',
            'mt': u'Thread',
            'my': u'Thread',
            'na': u'Thread',
            'nah': u'Thread',
            'nds': u'Thread',
            'ne': u'Thread',
            'nl': u'Thread',
            'nn': u'Thread',
            'no': u'Thread',
            'oc': u'Thread',
            'om': u'Thread',
            'pa': u'Thread',
            'pl': u'Thread',
            'ps': u'Thread',
            'pt': u'Tópico',
            'qu': u'Thread',
            'ro': u'Thread',
            'roa-rup': u'Thread',
            'ru': u'Thread',
            'rw': u'Thread',
            'sa': u'Thread',
            'scn': u'Thread',
            'sd': u'Thread',
            'sg': u'Thread',
            'sh': u'Thread',
            'si': u'Thread',
            'simple': u'Thread',
            'sk': u'Thread',
            'sl': u'Thread',
            'sm': u'Thread',
            'so': u'Thread',
            'sq': u'Thread',
            'sr': u'Thread',
            'ss': u'Thread',
            'st': u'Thread',
            'su': u'Thread',
            'sv': u'Thread',
            'sw': u'Thread',
            'ta': u'Thread',
            'te': u'Thread',
            'tg': u'Thread',
            'th': u'Thread',
            'ti': u'Thread',
            'tk': u'Thread',
            'tl': u'Thread',
            'tn': u'Thread',
            'tpi': u'Thread',
            'tr': u'Thread',
            'ts': u'Thread',
            'tt': u'Thread',
            'ug': u'Thread',
            'uk': u'Thread',
            'ur': u'Thread',
            'uz': u'Thread',
            'vi': u'Thread',
            'vo': u'Thread',
            'wa': u'Thread',
            'wo': u'Thread',
            'yi': u'Thread',
            'za': u'Thread',
            'zh': u'Thread',
            'zh-min-nan': u'Thread',
            'zu': u'Thread',
        }

        self.namespaces[91] = {
            'af': u'Thread talk',
            'als': u'Thread talk',
            'am': u'Thread talk',
            'an': u'Thread talk',
            'ang': u'Thread talk',
            'ar': u'Thread talk',
            'ast': u'Thread talk',
            'ay': u'Thread talk',
            'az': u'Thread talk',
            'be': u'Thread talk',
            'bg': u'Thread talk',
            'bn': u'Thread talk',
            'br': u'Thread talk',
            'bs': u'Thread talk',
            'ca': u'Thread talk',
            'chr': u'Thread talk',
            'co': u'Thread talk',
            'cs': u'Thread talk',
            'csb': u'Thread talk',
            'cy': u'Thread talk',
            'da': u'Thread talk',
            'de': u'Thread talk',
            'dv': u'Thread talk',
            'dz': u'Thread talk',
            'el': u'Thread talk',
            'en': u'Thread talk',
            'eo': u'Thread talk',
            'es': u'Thread talk',
            'et': u'Thread talk',
            'eu': u'Thread talk',
            'fa': u'Thread talk',
            'fi': u'Keskustelu viestiketjusta',
            'fj': u'Thread talk',
            'fo': u'Thread talk',
            'fr': u'Thread talk',
            'fy': u'Thread talk',
            'ga': u'Thread talk',
            'gd': u'Thread talk',
            'gl': u'Tópico discussão',
            'gn': u'Thread talk',
            'gu': u'Thread talk',
            'gv': u'Thread talk',
            'ha': u'Thread talk',
            'he': u'Thread talk',
            'hi': u'Thread talk',
            'hr': u'Thread talk',
            'hsb': u'Thread talk',
            'hu': u'Thread talk',
            'hy': u'Thread talk',
            'ia': u'Thread talk',
            'id': u'Thread talk',
            'ie': u'Thread talk',
            'ik': u'Thread talk',
            'io': u'Thread talk',
            'is': u'Thread talk',
            'it': u'Thread talk',
            'iu': u'Thread talk',
            'ja': u'Thread talk',
            'jbo': u'Thread talk',
            'jv': u'Thread talk',
            'ka': u'Thread talk',
            'kk': u'Thread talk',
            'kl': u'Thread talk',
            'km': u'Thread talk',
            'kn': u'Thread talk',
            'ko': u'Thread talk',
            'ks': u'Thread talk',
            'ku': u'Thread talk',
            'kw': u'Thread talk',
            'ky': u'Thread talk',
            'la': u'Thread talk',
            'lb': u'Thread talk',
            'li': u'Thread talk',
            'ln': u'Thread talk',
            'lo': u'Thread talk',
            'lt': u'Thread talk',
            'lv': u'Thread talk',
            'mg': u'Thread talk',
            'mi': u'Thread talk',
            'mk': u'Thread talk',
            'ml': u'Thread talk',
            'mn': u'Thread talk',
            'mr': u'Thread talk',
            'ms': u'Thread talk',
            'mt': u'Thread talk',
            'my': u'Thread talk',
            'na': u'Thread talk',
            'nah': u'Thread talk',
            'nds': u'Thread talk',
            'ne': u'Thread talk',
            'nl': u'Thread talk',
            'nn': u'Thread talk',
            'no': u'Thread talk',
            'oc': u'Thread talk',
            'om': u'Thread talk',
            'pa': u'Thread talk',
            'pl': u'Thread talk',
            'ps': u'Thread talk',
            'pt': u'Tópico discussão',
            'qu': u'Thread talk',
            'ro': u'Thread talk',
            'roa-rup': u'Thread talk',
            'ru': u'Thread talk',
            'rw': u'Thread talk',
            'sa': u'Thread talk',
            'scn': u'Thread talk',
            'sd': u'Thread talk',
            'sg': u'Thread talk',
            'sh': u'Thread talk',
            'si': u'Thread talk',
            'simple': u'Thread talk',
            'sk': u'Thread talk',
            'sl': u'Thread talk',
            'sm': u'Thread talk',
            'so': u'Thread talk',
            'sq': u'Thread talk',
            'sr': u'Thread talk',
            'ss': u'Thread talk',
            'st': u'Thread talk',
            'su': u'Thread talk',
            'sv': u'Thread talk',
            'sw': u'Thread talk',
            'ta': u'Thread talk',
            'te': u'Thread talk',
            'tg': u'Thread talk',
            'th': u'Thread talk',
            'ti': u'Thread talk',
            'tk': u'Thread talk',
            'tl': u'Thread talk',
            'tn': u'Thread talk',
            'tpi': u'Thread talk',
            'tr': u'Thread talk',
            'ts': u'Thread talk',
            'tt': u'Thread talk',
            'ug': u'Thread talk',
            'uk': u'Thread talk',
            'ur': u'Thread talk',
            'uz': u'Thread talk',
            'vi': u'Thread talk',
            'vo': u'Thread talk',
            'wa': u'Thread talk',
            'wo': u'Thread talk',
            'yi': u'Thread talk',
            'za': u'Thread talk',
            'zh': u'Thread talk',
            'zh-min-nan': u'Thread talk',
            'zu': u'Thread talk',
        }

        self.namespaces[92] = {
            'af': u'Summary',
            'als': u'Summary',
            'am': u'Summary',
            'an': u'Summary',
            'ang': u'Summary',
            'ar': u'Summary',
            'ast': u'Summary',
            'ay': u'Summary',
            'az': u'Summary',
            'be': u'Summary',
            'bg': u'Summary',
            'bn': u'Summary',
            'br': u'Summary',
            'bs': u'Summary',
            'ca': u'Summary',
            'chr': u'Summary',
            'co': u'Summary',
            'cs': u'Summary',
            'csb': u'Summary',
            'cy': u'Summary',
            'da': u'Summary',
            'de': u'Summary',
            'dv': u'Summary',
            'dz': u'Summary',
            'el': u'Summary',
            'en': u'Summary',
            'eo': u'Summary',
            'es': u'Summary',
            'et': u'Summary',
            'eu': u'Summary',
            'fa': u'Summary',
            'fi': u'Yhteenveto',
            'fj': u'Summary',
            'fo': u'Summary',
            'fr': u'Summary',
            'fy': u'Summary',
            'ga': u'Summary',
            'gd': u'Summary',
            'gl': u'Resumo',
            'gn': u'Summary',
            'gu': u'Summary',
            'gv': u'Summary',
            'ha': u'Summary',
            'he': u'Summary',
            'hi': u'Summary',
            'hr': u'Summary',
            'hsb': u'Summary',
            'hu': u'Summary',
            'hy': u'Summary',
            'ia': u'Summary',
            'id': u'Summary',
            'ie': u'Summary',
            'ik': u'Summary',
            'io': u'Summary',
            'is': u'Summary',
            'it': u'Summary',
            'iu': u'Summary',
            'ja': u'Summary',
            'jbo': u'Summary',
            'jv': u'Summary',
            'ka': u'Summary',
            'kk': u'Summary',
            'kl': u'Summary',
            'km': u'Summary',
            'kn': u'Summary',
            'ko': u'Summary',
            'ks': u'Summary',
            'ku': u'Summary',
            'kw': u'Summary',
            'ky': u'Summary',
            'la': u'Summary',
            'lb': u'Summary',
            'li': u'Summary',
            'ln': u'Summary',
            'lo': u'Summary',
            'lt': u'Summary',
            'lv': u'Summary',
            'mg': u'Summary',
            'mi': u'Summary',
            'mk': u'Summary',
            'ml': u'Summary',
            'mn': u'Summary',
            'mr': u'Summary',
            'ms': u'Summary',
            'mt': u'Summary',
            'my': u'Summary',
            'na': u'Summary',
            'nah': u'Summary',
            'nds': u'Summary',
            'ne': u'Summary',
            'nl': u'Summary',
            'nn': u'Summary',
            'no': u'Summary',
            'oc': u'Summary',
            'om': u'Summary',
            'pa': u'Summary',
            'pl': u'Summary',
            'ps': u'Summary',
            'pt': u'Resumo',
            'qu': u'Summary',
            'ro': u'Summary',
            'roa-rup': u'Summary',
            'ru': u'Summary',
            'rw': u'Summary',
            'sa': u'Summary',
            'scn': u'Summary',
            'sd': u'Summary',
            'sg': u'Summary',
            'sh': u'Summary',
            'si': u'Summary',
            'simple': u'Summary',
            'sk': u'Summary',
            'sl': u'Summary',
            'sm': u'Summary',
            'so': u'Summary',
            'sq': u'Summary',
            'sr': u'Summary',
            'ss': u'Summary',
            'st': u'Summary',
            'su': u'Summary',
            'sv': u'Summary',
            'sw': u'Summary',
            'ta': u'Summary',
            'te': u'Summary',
            'tg': u'Summary',
            'th': u'Summary',
            'ti': u'Summary',
            'tk': u'Summary',
            'tl': u'Summary',
            'tn': u'Summary',
            'tpi': u'Summary',
            'tr': u'Summary',
            'ts': u'Summary',
            'tt': u'Summary',
            'ug': u'Summary',
            'uk': u'Summary',
            'ur': u'Summary',
            'uz': u'Summary',
            'vi': u'Summary',
            'vo': u'Summary',
            'wa': u'Summary',
            'wo': u'Summary',
            'yi': u'Summary',
            'za': u'Summary',
            'zh': u'Summary',
            'zh-min-nan': u'Summary',
            'zu': u'Summary',
        }

        self.namespaces[93] = {
            'af': u'Summary talk',
            'als': u'Summary talk',
            'am': u'Summary talk',
            'an': u'Summary talk',
            'ang': u'Summary talk',
            'ar': u'Summary talk',
            'ast': u'Summary talk',
            'ay': u'Summary talk',
            'az': u'Summary talk',
            'be': u'Summary talk',
            'bg': u'Summary talk',
            'bn': u'Summary talk',
            'br': u'Summary talk',
            'bs': u'Summary talk',
            'ca': u'Summary talk',
            'chr': u'Summary talk',
            'co': u'Summary talk',
            'cs': u'Summary talk',
            'csb': u'Summary talk',
            'cy': u'Summary talk',
            'da': u'Summary talk',
            'de': u'Summary talk',
            'dv': u'Summary talk',
            'dz': u'Summary talk',
            'el': u'Summary talk',
            'en': u'Summary talk',
            'eo': u'Summary talk',
            'es': u'Summary talk',
            'et': u'Summary talk',
            'eu': u'Summary talk',
            'fa': u'Summary talk',
            'fi': u'Keskustelu yhteenvedosta',
            'fj': u'Summary talk',
            'fo': u'Summary talk',
            'fr': u'Summary talk',
            'fy': u'Summary talk',
            'ga': u'Summary talk',
            'gd': u'Summary talk',
            'gl': u'Resumo discussão',
            'gn': u'Summary talk',
            'gu': u'Summary talk',
            'gv': u'Summary talk',
            'ha': u'Summary talk',
            'he': u'Summary talk',
            'hi': u'Summary talk',
            'hr': u'Summary talk',
            'hsb': u'Summary talk',
            'hu': u'Summary talk',
            'hy': u'Summary talk',
            'ia': u'Summary talk',
            'id': u'Summary talk',
            'ie': u'Summary talk',
            'ik': u'Summary talk',
            'io': u'Summary talk',
            'is': u'Summary talk',
            'it': u'Summary talk',
            'iu': u'Summary talk',
            'ja': u'Summary talk',
            'jbo': u'Summary talk',
            'jv': u'Summary talk',
            'ka': u'Summary talk',
            'kk': u'Summary talk',
            'kl': u'Summary talk',
            'km': u'Summary talk',
            'kn': u'Summary talk',
            'ko': u'Summary talk',
            'ks': u'Summary talk',
            'ku': u'Summary talk',
            'kw': u'Summary talk',
            'ky': u'Summary talk',
            'la': u'Summary talk',
            'lb': u'Summary talk',
            'li': u'Summary talk',
            'ln': u'Summary talk',
            'lo': u'Summary talk',
            'lt': u'Summary talk',
            'lv': u'Summary talk',
            'mg': u'Summary talk',
            'mi': u'Summary talk',
            'mk': u'Summary talk',
            'ml': u'Summary talk',
            'mn': u'Summary talk',
            'mr': u'Summary talk',
            'ms': u'Summary talk',
            'mt': u'Summary talk',
            'my': u'Summary talk',
            'na': u'Summary talk',
            'nah': u'Summary talk',
            'nds': u'Summary talk',
            'ne': u'Summary talk',
            'nl': u'Summary talk',
            'nn': u'Summary talk',
            'no': u'Summary talk',
            'oc': u'Summary talk',
            'om': u'Summary talk',
            'pa': u'Summary talk',
            'pl': u'Summary talk',
            'ps': u'Summary talk',
            'pt': u'Resumo discussão',
            'qu': u'Summary talk',
            'ro': u'Summary talk',
            'roa-rup': u'Summary talk',
            'ru': u'Summary talk',
            'rw': u'Summary talk',
            'sa': u'Summary talk',
            'scn': u'Summary talk',
            'sd': u'Summary talk',
            'sg': u'Summary talk',
            'sh': u'Summary talk',
            'si': u'Summary talk',
            'simple': u'Summary talk',
            'sk': u'Summary talk',
            'sl': u'Summary talk',
            'sm': u'Summary talk',
            'so': u'Summary talk',
            'sq': u'Summary talk',
            'sr': u'Summary talk',
            'ss': u'Summary talk',
            'st': u'Summary talk',
            'su': u'Summary talk',
            'sv': u'Summary talk',
            'sw': u'Summary talk',
            'ta': u'Summary talk',
            'te': u'Summary talk',
            'tg': u'Summary talk',
            'th': u'Summary talk',
            'ti': u'Summary talk',
            'tk': u'Summary talk',
            'tl': u'Summary talk',
            'tn': u'Summary talk',
            'tpi': u'Summary talk',
            'tr': u'Summary talk',
            'ts': u'Summary talk',
            'tt': u'Summary talk',
            'ug': u'Summary talk',
            'uk': u'Summary talk',
            'ur': u'Summary talk',
            'uz': u'Summary talk',
            'vi': u'Summary talk',
            'vo': u'Summary talk',
            'wa': u'Summary talk',
            'wo': u'Summary talk',
            'yi': u'Summary talk',
            'za': u'Summary talk',
            'zh': u'Summary talk',
            'zh-min-nan': u'Summary talk',
            'zu': u'Summary talk',
        }

        self.namespaces[100] = {
            'bg': u'Словоформи',
            'bn': u'উইকিসরাস',
            'bs': u'Portal',
            'cy': u'Atodiad',
            'el': u'Παράρτημα',
            'en': u'Appendix',
            'es': u'Apéndice',
            'fa': u'پیوست',
            'fi': u'Liite',
            'fr': u'Annexe',
            'ga': u'Aguisín',
            'gl': u'Apéndice',
            'he': u'נספח',
            'it': u'Appendice',
            'ko': u'부록',
            'lb': u'Annexen',
            'lt': u'Sąrašas',
            'no': u'Tillegg',
            'oc': u'Annèxa',
            'pl': u'Aneks',
            'pt': u'Apêndice',
            'ro': u'Portal',
            'ru': [u'Приложение', u'Appendix'],
            'sr': u'Портал',
            'tr': u'Portal',
            'uk': u'Додаток',
        }
        self.namespaces[101] = {
            'bg': u'Словоформи беседа',
            'bn': u'উইকিসরাস আলোচনা',
            'bs': u'Razgovor o Portalu',
            'cy': u'Sgwrs Atodiad',
            'el': u'Συζήτηση παραρτήματος',
            'en': u'Appendix talk',
            'es': u'Apéndice Discusión',
            'fa': u'بحث پیوست',
            'fi': u'Keskustelu liitteestä',
            'fr': u'Discussion Annexe',
            'ga': u'Plé aguisín',
            'gl': u'Conversa apéndice',
            'he': u'שיחת נספח',
            'it': u'Discussioni appendice',
            'ko': u'부록 토론',
            'lb': u'Annexen Diskussioun',
            'lt': u'Sąrašo aptarimas',
            'no': u'Tilleggdiskusjon',
            'oc': u'Discussion Annèxa',
            'pl': u'Dyskusja aneksu',
            'pt': u'Apêndice Discussão',
            'ro': u'Discuţie Portal',
            'ru': [u'Обсуждение приложения', u'Appendix talk'],
            'sr': u'Разговор о порталу',
            'tr': u'Portal tartışma',
            'uk': u'Обговорення додатка',
        }

        self.namespaces[102] = {
            'bs': u'Indeks',
            'cy': u'Odliadur',
            'de': u'Verzeichnis',
            'en': u'Concordance',
            'fr': u'Transwiki',
            'ia': u'Appendice',
            'lt': u'Priedas',
            'pl': u'Indeks',
            'pt': u'Vocabulário',
            'ro': u'Apendice',
            'ru': [u'Конкорданс', u'Concordance'],
            'sv': u'Appendix',
            'uk': u'Індекс',
        }

        self.namespaces[103] = {
            'bs': u'Razgovor o Indeksu',
            'cy': u'Sgwrs Odliadur',
            'de': u'Verzeichnis Diskussion',
            'en': u'Concordance talk',
            'fr': u'Discussion Transwiki',
            'ia': u'Discussion Appendice',
            'lt': u'Priedo aptarimas',
            'pl': u'Dyskusja indeksu',
            'pt': u'Vocabulário Discussão',
            'ro': u'Discuţie Apendice',
            'ru': [u'Обсуждение конкорданса', u'Concordance talk'],
            'sv': u'Appendixdiskussion',
            'uk': u'Обговорення індексу',
        }

        self.namespaces[104] = {
            'bs': u'Dodatak',
            'cy': u'WiciSawrws',
            'de': u'Thesaurus',
            'en': u'Index',
            'fr': u'Portail',
            'pl': u'Portal',
            'pt': u'Rimas',
            'ru': [u'Индекс', u'Index'],
            'sv': u'Rimord',
        }

        self.namespaces[105] = {
            'bs': u'Razgovor o Dodatku',
            'cy': u'Sgwrs WiciSawrws',
            'de': u'Thesaurus Diskussion',
            'en': u'Index talk',
            'fr': u'Discussion Portail',
            'pl': u'Dyskusja portalu',
            'pt': u'Rimas Discussão',
            'ru': [u'Обсуждение индекса', u'Index talk'],
            'sv': u'Rimordsdiskussion',
        }

        self.namespaces[106] = {
            'en': u'Rhymes',
            'fr': u'Thésaurus',
            'is': u'Viðauki',
            'pt': u'Portal',
            'ru': [u'Рифмы', u'Rhymes'],
            'sv': u'Transwiki',
        }

        self.namespaces[107] = {
            'en': u'Rhymes talk',
            'fr': u'Discussion Thésaurus',
            'is': u'Viðaukaspjall',
            'pt': u'Portal Discussão',
            'ru': [u'Обсуждение рифм', u'Rhymes talk'],
            'sv': u'Transwikidiskussion',
        }

        self.namespaces[108] = {
            'en': u'Transwiki',
            'pt': u'Citações',
        }

        self.namespaces[109] = {
            'en': u'Transwiki talk',
            'pt': u'Citações Discussão',
        }

        self.namespaces[110] = {
            'en': u'Wikisaurus',
            'is': u'Samheitasafn',
            'ko': u'미주알고주알',
        }

        self.namespaces[111] = {
            'en': u'Wikisaurus talk',
            'is': u'Samheitasafnsspjall',
            'ko': u'미주알고주알 토론',
        }

        self.namespaces[112] = {
         #   'en': u'WT',
        }

        self.namespaces[113] = {
         #   'en': u'WT talk',
        }

        self.namespaces[114] = {
            'en': u'Citations',
        }

        self.namespaces[115] = {
            'en': u'Citations talk',
        }

        self.namespaces[116] = {
            'en': u'Sign gloss',
        }

        self.namespaces[117] = {
            'en': u'Sign gloss talk',
        }

        # Other than most Wikipedias, page names must not start with a capital
        # letter on ALL Wiktionaries.
        self.nocapitalize = self.langs.keys()

        # Global bot allowed languages on http://meta.wikimedia.org/wiki/Bot_policy/Implementation#Current_implementation
        self.cross_allowed = [
            'ang', 'ast', 'az', 'bg', 'bn', 'da', 'eo', 'es', 'fa', 'fy', 'ga', 'gd', 'hu', 
            'ia', 'ie', 'ik', 'jv', 'ka', 'li', 'lt', 'mk', 'nl', 'no', 'oc', 'pt', 'sk', 'tg', 'th', 'ti', 
            'ts', 'ug', 'uk', 'vo', 'za', 'zh-min-nan', 'zh', 'zu', 
        ]
        # CentralAuth cross avaliable projects.
        self.cross_projects = [
            'wikipedia', 'wikibooks', 'wikiquote', 'wikisource', 'wikinews', 'wikiversity',
            'meta', 'mediawiki', 'test', 'incubator', 'commons', 'species'
        ]
        self.obsolete = {
            'aa': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Afar_Wiktionary
            'ab': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Abkhaz_Wiktionary
            'ak': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Akan_Wiktionary
            'as': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Assamese_Wiktionary
            'av': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Avar_Wiktionary
            'ba': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Bashkir_Wiktionary
            'bh': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Bihari_Wiktionary
            'bi': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Bislama_Wiktionary
            'bm': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Bambara_Wiktionary
            'bo': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Tibetan_Wiktionary
            'ch': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Chamorro_Wiktionary
            'cr': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Nehiyaw_Wiktionary
            'dk': 'da',
            'jp': 'ja',
            'mh': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Marshallese_Wiktionary
            'mo': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Moldovan_Wiktionary
            'minnan':'zh-min-nan',
            'nb': 'no',
            'or': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Oriya_Wiktionary
            'pi': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Pali_Bhasa_Wiktionary
            'rm': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Rhaetian_Wiktionary
            'rn': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Kirundi_Wiktionary
            'sc': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Sardinian_Wiktionary
            'sn': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Shona_Wiktionary
            'to': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Tongan_Wiktionary
            'tlh': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Klingon_Wiktionary
            'tw': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Twi_Wiktionary
            'tokipona': None,
            'xh': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Xhosa_Wiktionary
            'yo': None, # http://meta.wikimedia.org/wiki/Proposals_for_closing_projects/Closure_of_Yoruba_Wiktionary
            'zh-tw': 'zh',
            'zh-cn': 'zh'
        }

        # Order for fy: alphabetical by code, but y counts as i
        # TODO: This code is duplicated from wikipedia_family.py
        def fycomp(x,y):
            x = x.replace("y","i")+x.count("y")*"!"
            y = y.replace("y","i")+y.count("y")*"!"
            return cmp(x,y)
        self.fyinterwiki = self.alphabetic[:]
        self.fyinterwiki.sort(fycomp)

        # Which languages have a special order for putting interlanguage links,
        # and what order is it? If a language is not in interwiki_putfirst,
        # alphabetical order on language code is used. For languages that are in
        # interwiki_putfirst, interwiki_putfirst is checked first, and
        # languages are put in the order given there. All other languages are put
        # after those, in code-alphabetical order.

        self.interwiki_putfirst = {
            'en': self.alphabetic,
            'et': self.alphabetic,
            'fi': self.alphabetic,
            'fy': self.fyinterwiki,
            'he': ['en'],
            'hu': ['en'],
            'pl': self.alphabetic,
            'simple': self.alphabetic
        }

        self.interwiki_on_one_line = ['pl']

        self.interwiki_attop = ['pl']

    def version(self, code):
        return '1.16wmf4'

    def shared_image_repository(self, code):
        return ('commons', 'commons')

    if family.config.SSL_connection:
        def hostname(self, code):
            return 'secure.wikimedia.org'

        def protocol(self, code):
            return 'https'

        def scriptpath(self, code):
            return '/%s/%s/w' % (self.name, code)

        def nicepath(self, code):
            return '/%s/%s/wiki/' % (self.name, code)
